name: Linting

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install 3.12

      - name: Install pre-commit
        shell: bash
        run: uv venv && source .venv/bin/activate && uv pip install pre-commit

      - name: Run linter
        shell: bash
        run: uv run -- pre-commit run -a
